---

- name: make directories
  file: path=~/{{item}} state=directory
  with_items:
    - dev
    - scratch
    - tmp

- name: get git repos
  git: repo={{item.repo}} dest={{item.dest}} version={{item.version}}
  with_items:
    -
      repo: https://github.com/editorconfig/editorconfig-core-c.git
      dest: ~/dev/editorconfig-core-c
      version: 8e488cb3e78924d4c66c4cd39649b4c77932ad1c
    -
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: ~/dev/bash-git-prompt
      version: 134219ea4bb02b00ed18de5c85daf1724328c55c
    -
      repo: https://github.com/dominikh/yasnippet-go
      dest: ~/dev/yasnippet-go
      version: c92cc86aa4c094af64a01b6a24ac6ce10b717bb4

- name: build editorconfig core
  command: cmake .
  args:
    chdir: ~/dev/editorconfig-core-c
    creates: ~/dev/editorconfig-core-c/bin/editorconfig

- name: install editorconfig core
  become: yes
  command: make install
  args:
    chdir: "{{ansible_env.HOME}}/dev/editorconfig-core-c"
    creates: /usr/local/bin/editorconfig

- name: get emacs-config
  hg: repo=ssh://babbageclunk.com/hg/emacs-config dest=~/dev/emacs-config

- name: put .emacs in place
  file: dest=~/{{item.dest}} src=~/dev/{{item.src}} state=link force=yes
  with_items:
    - {src: emacs-config/.emacs, dest: .emacs}
    - {src: emacs-config, dest: .emacs.d}
