---

- name: make go path
  file: path=~/dev/go state=directory

- name: get go tools
  command: go get {{item.src}}
  args:
    creates: ~/dev/go/bin/{{item.bin}}
  with_items:
    - {src: github.com/rogpeppe/godeps, bin: godeps}
    - {src: github.com/rogpeppe/godef, bin: godef}

- name: get juju source
  command: go get -d github.com/juju/juju/...
  ignore_errors: yes
  # For some reason, it complains about (I think) pinned dependencies between azure-sdk-for-go and go-autorest.

- name: update godeps
  command: godeps -u dependencies.tsv
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: get juju source
  command: go get -d github.com/juju/juju/...
  # There's bound to be a better way to do this.

- name: install juju dependencies
  command: make install-dependencies
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: install juju
  command: go install github.com/juju/juju/...
  args:
    creates: ~/dev/go/bin/juju

- name: switch origin to my fork
  command: git remote set-url origin git@github.com:babbageclunk/juju.git
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: list remotes
  command: git remote -v
  args:
    chdir: ~/dev/go/src/github.com/juju/juju
  register: juju_remotes

- name: maybe add upstream repo
  command: git remote add upstream https://github.com/juju/juju.git
  when: juju_remotes.stdout.find('upstream') == -1
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: add pre-push hook
  file:
    src: ~/dev/go/src/github.com/juju/juju/scripts/pre-push.bash
    dest: ~/dev/go/src/github.com/juju/juju/.git/hooks/pre-push
    state: link
