---

- name: make go path
  file: path=~/dev/go state=link src=/opt/go

- name: get go tools
  command: go get {{item.src}}
  args:
    creates: ~/dev/go/bin/{{item.bin}}
  with_items:
    - {src: github.com/rogpeppe/godeps, bin: godeps}
    - {src: github.com/rogpeppe/godef, bin: godef}
    - {src: golang.org/x/tools/cmd/guru, bin: guru}
    - {src: golang.org/x/tools/cmd/gorename, bin: gorename}
    - {src: github.com/nsf/gocode, bin: gocode}
    - {src: github.com/github/hub, bin: hub}

- name: get juju source
  command: go get -d github.com/juju/juju/...
  ignore_errors: yes
  # For some reason, it complains about (I think) pinned dependencies between azure-sdk-for-go and go-autorest.

- name: update godeps
  command: godeps -u dependencies.tsv
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: get juju source
  command: go get -d github.com/juju/juju/...
  # There's bound to be a better way to do this.

- name: install juju dependencies
  command: make install-dependencies
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: install juju
  command: go install github.com/juju/juju/...
  args:
    creates: ~/dev/go/bin/juju

- name: switch origin to my fork
  command: git remote set-url origin git@github.com:babbageclunk/juju.git
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: list remotes
  command: git remote -v
  args:
    chdir: ~/dev/go/src/github.com/juju/juju
  register: juju_remotes

- name: maybe add upstream repo
  command: git remote add upstream https://github.com/juju/juju.git
  when: juju_remotes.stdout.find('upstream') == -1
  args:
    chdir: ~/dev/go/src/github.com/juju/juju

- name: add pre-push hook
  file:
    src: ~/dev/go/src/github.com/juju/juju/scripts/pre-push.bash
    dest: ~/dev/go/src/github.com/juju/juju/.git/hooks/pre-push
    state: link

- name: make juju link dir
  file: src=~/dev/go/src/github.com/juju/juju dest=~/juju state=link

- name: get kvm-setup utils
  git: repo={{item.repo}} dest={{item.dest}}
  with_items:
    -
      repo: git@github.com:babbageclunk/ubuntu-fan-hacks.git
      dest: ~/dev/ubuntu-fan-hacks
    -
      repo: https://github.com/frobware/kvm-maas.git
      dest: ~/dev/kvm-maas

# If this fails it's probably waiting for access to the ssh key - unlock it.
- name: CI tools
  git: repo={{item.repo}} dest=~/dev/{{item.dest}}
  with_items:
    - repo: git+ssh://2-xtian@git.launchpad.net/~juju-qa/+git/cloud-city
      dest: cloud-city

# Sometimes when linking juju we run out of memory completely - kill
# the linker instead of hanging.
# See http://askubuntu.com/questions/398236/oom-killer-not-working
- name: make OOM killer kill compile
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'vm.oom_kill_allocating_task = 1'
