---

- name: apt packages
  become: yes
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - git
    - emacs24
    - htop

- name: upgrade pip
  become: yes
  pip: name=pip extra_args=--upgrade

