---

- name: apt keys
  become: yes
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }}
  with_items:
    - {keyserver: keyserver.ubuntu.com, id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E}  # Dropbox
    - {keyserver: keyserver.ubuntu.com, id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991}  # Google

- name: apt repos
  become: yes
  apt_repository: repo='{{ item }}' state=present update_cache=yes
  with_items:
    - 'deb http://linux.dropbox.com/ubuntu wily main'
    - 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    - ppa:tmate.io/archive
    - ppa:ubuntu-lxc/lxd-stable
    - ppa:maas-maintainers/experimental3

- name: build dependencies
  become: yes
  apt: pkg=python2.7 state=build-dep

- name: apt packages
  become: yes
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-gpgme
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - git
    - git-gui
    - gitk
    - emacs24
    - htop
    - dropbox
    - mercurial
    - libpcre3-dev
    - cmake
    - bzr
    - indicator-multiload
    - google-chrome-stable
    - powertop
    - pm-utils
    - virt-manager
    - tmux
    - software-properties-common
    - tmate
    - qemu-system
    - libvirt-bin
    - maas-cli
    - openssh-server
    - unity-tweak-tool
    - qemu-kvm
    - cloc
    - lxd
    - lxd-client
    - tree
    - gtypist
    - apt-cacher-ng
    - juju-mongodb3.2
    - ipython3
    - python3-pip

- name: upgrade pip
  become: yes
  pip: name=pip extra_args=--upgrade

- name: python packages
  become: yes
  pip: name={{item}}
  with_items:
    - ipython
    - ansible
    - virtualenv
    - jedi
    - pyflakes
    - RBTools
